### ISSUE TITLE
Invalid CU number in rx6900xt

### ISSUE THREAD

**Issue by ClavosPL** [PhoenixMinerDevTeam/PhoenixMiner#1]
PhoenixMiner 5.5 c see only 40 CU of GPU from rx6900xt
rx6900xt has 80CU- s......

**Comment by PhoenixMinerDevTeam** [comment]
It's already fixed in the upcoming version. 

Note that OpenCL actually reports 40 CUs (the older Navi GPUs like 5700XT had the same behavior) and the difference is because of the way Navi CUs are organized. Do not expect any difference in hashrate because of this - the GPU is already fully utilized regardless of the "wrong" CU number reported.
