### ISSUE TITLE
RX 580 config example to reach 30mh/s without bios modding

### ISSUE THREAD

**Issue by pedrohrcunha** [PhoenixMinerDevTeam/PhoenixMiner#10]
Can anyone help me out setting straps and clocks, or anything like that? I'm aware (atleast in my case) that an AMD card can crash windows with pretty much any command related to OC, but I will give it a try. I got like a hundred blue screens with thread_stuck_device_driver.

**Comment by PhoenixMinerDevTeam** [comment]
Try the following options:
`-mt 1 -rxboost 1 -mclock 2000 -cclock 1100 -cvddc 900`

Note that you will need to run PhoenixMiner.exe as administrator for `-rxboost 1` to work. 

If these work without crashing, you can start experimenting with `-mt 2` instead of `-mt 1`, increasing the memory clock further (e.g. `-mclock 2050`, and so on). We are working on better straps for Polaris cards but it won't be ready for the next release of PhoenixMiner.
