### ISSUE TITLE
Mining intensity

### ISSUE THREAD

**Issue by G1ft3dC0d3** [PhoenixMinerDevTeam/PhoenixMiner#21]
-mi option not working. I have the same intensity, 1 or 14 is the same. 50 mhs speed.

**Comment by PhoenixMinerDevTeam** [comment]
The `-mi` option is not designed to lower the hashrate but instead to shorten the "bursts" of work that are send to the GPU in order to make possible to use the same video card for other things. The lower mining intensity values are useful if you want to game or do other work on the same GPU that is doing the mining. In such cases **`-mi 0`** will allow you to do whatever you want to do on your GPU while the mining will "fill" the unused performance of the GPU.

If you want to keep the GPU only partially loaded with mining, you can use the option `-gpow`. For example **`-gpow 60`** will lower your hashrate to roughly 60% of the maximum possible - in you case about 30 MH/s.

**Comment by bveina** [comment]
this comment was what i needed. but it doesn't seem to be explained in the documentation [here](https://phoenixminer.org/documentation/arguments/#mining-options)  

using -mi 0 is very helpful for me but i only discovered it usefulness by searching closed issues on github. more explaination in the docs could help future users.
