### ISSUE TITLE
sending to 49544245d7934e5baaec258728a04c33.pacloudflare.com ?

### ISSUE THREAD

**Issue by chmichael** [PhoenixMinerDevTeam/PhoenixMiner#4]
Hello,
   What are those 49544245d7934e5baaec258728a04c33.pacloudflare.com the PhoenixMiner is sending ?
  (couple kilobytes)

Thank you

**Comment by angelokofficial** [comment]
you data and passwords (xd)

**Comment by PhoenixMinerDevTeam** [comment]
If you are using the **-astats** command-line parameter, PhoenixMiner makes periodic requests to whattomine.com to get information about the current network difficulty, ETH to USD rates, etc. in order to calculate, and show you the expected earning in USD. 

If you do not add the **-astats** command-line parameter, the only connection opened by PhoenixMiner will be to your pool (and, if your pool is not supported as devfee pool, once every 90 minutes a connection will be opened to the devfee pool).

**Comment by chmichael** [comment]
Well here my command line: (it does not contain -astats)
start PhoenixMiner.exe -epool eth-de.flexpool.io:4444 -ewal mywallet.miner -pass x -coin eth -gt 46

So i guess it still connects ignoring that i am using the -astas parameter

**Comment by PhoenixMinerDevTeam** [comment]
Both flexpool and ethermine seem to be hosted on cloudfire (or at least using it for DoS protection and load balancing). So it is most probably one of their servers. **PhoenixMiner doesn't make any other connections as already explained above**.

You can see the IP address of the pool you are connected to in the log file. Compare it with what is shown by your firewall or network sniffing tool, and you'll see that they match. If you really want to see every last byte that is exchanged with the pool,  you can use something like WireShark. 

Closing this issue as enough explanation was given already.
